/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabSetupRouteImport } from './routes/lab-setup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as TestParametersIndexRouteImport } from './routes/test-parameters/index'
import { Route as LabManagementIndexRouteImport } from './routes/lab-management/index'
import { Route as LabDetailsIndexRouteImport } from './routes/lab-details/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as TestResultsTestIdRouteImport } from './routes/test-results/$testId'
import { Route as PatientsRegisterRouteImport } from './routes/patients/register'
import { Route as PatientsIdRouteImport } from './routes/patients/$id'
import { Route as BillsIdRouteImport } from './routes/bills/$id'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as BillsBillIdRouteImport } from './routes/bills/bill.$id'
import { Route as BillsBillRouteImport } from './routes/bills/bill.'

const LabSetupRoute = LabSetupRouteImport.update({
  id: '/lab-setup',
  path: '/lab-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestParametersIndexRoute = TestParametersIndexRouteImport.update({
  id: '/test-parameters/',
  path: '/test-parameters/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabManagementIndexRoute = LabManagementIndexRouteImport.update({
  id: '/lab-management/',
  path: '/lab-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDetailsIndexRoute = LabDetailsIndexRouteImport.update({
  id: '/lab-details/',
  path: '/lab-details/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultsTestIdRoute = TestResultsTestIdRouteImport.update({
  id: '/test-results/$testId',
  path: '/test-results/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRegisterRoute = PatientsRegisterRouteImport.update({
  id: '/patients/register',
  path: '/patients/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdRoute = BillsBillIdRouteImport.update({
  id: '/bills/bill/$id',
  path: '/bills/bill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillRoute = BillsBillRouteImport.update({
  id: '/bills/bill/',
  path: '/bills/bill/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lab-setup': typeof LabSetupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/bills/$id': typeof BillsIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/register': typeof PatientsRegisterRoute
  '/test-results/$testId': typeof TestResultsTestIdRoute
  '/doctors': typeof DoctorsIndexRoute
  '/lab-details': typeof LabDetailsIndexRoute
  '/lab-management': typeof LabManagementIndexRoute
  '/test-parameters': typeof TestParametersIndexRoute
  '/tests': typeof TestsIndexRoute
  '/bills/bill': typeof BillsBillRoute
  '/bills/bill/$id': typeof BillsBillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lab-setup': typeof LabSetupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/bills/$id': typeof BillsIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/register': typeof PatientsRegisterRoute
  '/test-results/$testId': typeof TestResultsTestIdRoute
  '/doctors': typeof DoctorsIndexRoute
  '/lab-details': typeof LabDetailsIndexRoute
  '/lab-management': typeof LabManagementIndexRoute
  '/test-parameters': typeof TestParametersIndexRoute
  '/tests': typeof TestsIndexRoute
  '/bills/bill': typeof BillsBillRoute
  '/bills/bill/$id': typeof BillsBillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lab-setup': typeof LabSetupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/bills/$id': typeof BillsIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/register': typeof PatientsRegisterRoute
  '/test-results/$testId': typeof TestResultsTestIdRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/lab-details/': typeof LabDetailsIndexRoute
  '/lab-management/': typeof LabManagementIndexRoute
  '/test-parameters/': typeof TestParametersIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/bills/bill/': typeof BillsBillRoute
  '/bills/bill/$id': typeof BillsBillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/lab-setup'
    | '/admin/dashboard'
    | '/bills/$id'
    | '/patients/$id'
    | '/patients/register'
    | '/test-results/$testId'
    | '/doctors'
    | '/lab-details'
    | '/lab-management'
    | '/test-parameters'
    | '/tests'
    | '/bills/bill'
    | '/bills/bill/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/lab-setup'
    | '/admin/dashboard'
    | '/bills/$id'
    | '/patients/$id'
    | '/patients/register'
    | '/test-results/$testId'
    | '/doctors'
    | '/lab-details'
    | '/lab-management'
    | '/test-parameters'
    | '/tests'
    | '/bills/bill'
    | '/bills/bill/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/lab-setup'
    | '/admin/dashboard'
    | '/bills/$id'
    | '/patients/$id'
    | '/patients/register'
    | '/test-results/$testId'
    | '/doctors/'
    | '/lab-details/'
    | '/lab-management/'
    | '/test-parameters/'
    | '/tests/'
    | '/bills/bill/'
    | '/bills/bill/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LabSetupRoute: typeof LabSetupRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BillsIdRoute: typeof BillsIdRoute
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsRegisterRoute: typeof PatientsRegisterRoute
  TestResultsTestIdRoute: typeof TestResultsTestIdRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  LabDetailsIndexRoute: typeof LabDetailsIndexRoute
  LabManagementIndexRoute: typeof LabManagementIndexRoute
  TestParametersIndexRoute: typeof TestParametersIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  BillsBillRoute: typeof BillsBillRoute
  BillsBillIdRoute: typeof BillsBillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lab-setup': {
      id: '/lab-setup'
      path: '/lab-setup'
      fullPath: '/lab-setup'
      preLoaderRoute: typeof LabSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-parameters/': {
      id: '/test-parameters/'
      path: '/test-parameters'
      fullPath: '/test-parameters'
      preLoaderRoute: typeof TestParametersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-management/': {
      id: '/lab-management/'
      path: '/lab-management'
      fullPath: '/lab-management'
      preLoaderRoute: typeof LabManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-details/': {
      id: '/lab-details/'
      path: '/lab-details'
      fullPath: '/lab-details'
      preLoaderRoute: typeof LabDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-results/$testId': {
      id: '/test-results/$testId'
      path: '/test-results/$testId'
      fullPath: '/test-results/$testId'
      preLoaderRoute: typeof TestResultsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/register': {
      id: '/patients/register'
      path: '/patients/register'
      fullPath: '/patients/register'
      preLoaderRoute: typeof PatientsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/bill/$id': {
      id: '/bills/bill/$id'
      path: '/bills/bill/$id'
      fullPath: '/bills/bill/$id'
      preLoaderRoute: typeof BillsBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/bill/': {
      id: '/bills/bill/'
      path: '/bills/bill'
      fullPath: '/bills/bill'
      preLoaderRoute: typeof BillsBillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LabSetupRoute: LabSetupRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BillsIdRoute: BillsIdRoute,
  PatientsIdRoute: PatientsIdRoute,
  PatientsRegisterRoute: PatientsRegisterRoute,
  TestResultsTestIdRoute: TestResultsTestIdRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  LabDetailsIndexRoute: LabDetailsIndexRoute,
  LabManagementIndexRoute: LabManagementIndexRoute,
  TestParametersIndexRoute: TestParametersIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  BillsBillRoute: BillsBillRoute,
  BillsBillIdRoute: BillsBillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
